import Link from "next/link";
import { auth } from "@clerk/nextjs/server";
import {
  ArrowRight,
  Brain,
  ChevronRight,
  Cloud,
  LayoutTemplate,
  Luggage,
  MessageSquare,
  PackageOpen,
  Share2,
} from "lucide-react";

const steps = [
  {
    number: "01",
    title: "Describe Your Trip",
    description: "Destination, dates, trip type and activities.",
  },
  {
    number: "02",
    title: "AI Generates Your List",
    description:
      "Claude AI personalizes based on weather and your history.",
  },
  {
    number: "03",
    title: "Pack With Confidence",
    description:
      "Check items off, get SMS reminders, never forget anything.",
  },
];

const features = [
  {
    icon: Brain,
    title: "AI Packing Lists",
    description:
      "Personalized packing lists generated by Claude AI for every trip.",
  },
  {
    icon: Cloud,
    title: "Live Weather Data",
    description:
      "Forecasts for your destination shape what you actually need to bring.",
  },
  {
    icon: MessageSquare,
    title: "SMS Reminders",
    description:
      "Get text reminders before departure so nothing gets left behind.",
  },
  {
    icon: PackageOpen,
    title: "Unpack Mode",
    description:
      "Track what you actually used to make your next list even smarter.",
  },
  {
    icon: LayoutTemplate,
    title: "Trip Templates",
    description:
      "Save your favorite packing setups and reuse them for future trips.",
  },
  {
    icon: Share2,
    title: "Shareable Lists",
    description:
      "Share packing lists with travel companions in a single click.",
  },
];

export default async function Home() {
  const { userId } = await auth();

  return (
    <div className="flex min-h-screen flex-col bg-slate-950 text-white">
      {/* Navbar */}
      <header className="sticky top-0 z-50 border-b border-slate-800/50 bg-slate-950/80 backdrop-blur-md">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2 font-bold">
            <Luggage className="size-5 text-indigo-500" />
            <span>PackMind</span>
          </Link>
          <div className="flex items-center gap-2">
            {userId ? (
              <Link
                href="/dashboard"
                className="rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 px-4 py-2 text-sm font-medium text-white transition-opacity hover:opacity-90"
              >
                Go to Dashboard
              </Link>
            ) : (
              <>
                <Link
                  href="/sign-in"
                  className="rounded-xl px-4 py-2 text-sm font-medium text-slate-300 transition-colors hover:bg-slate-900 hover:text-white"
                >
                  Sign In
                </Link>
                <Link
                  href="/sign-up"
                  className="rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 px-4 py-2 text-sm font-medium text-white transition-opacity hover:opacity-90"
                >
                  Get Started
                </Link>
              </>
            )}
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="relative flex min-h-screen items-center justify-center overflow-hidden px-6">
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 flex items-center justify-center"
        >
          <div className="h-[36rem] w-[36rem] rounded-full bg-[radial-gradient(circle,rgba(99,102,241,0.25),transparent_70%)]" />
        </div>

        <div className="relative mx-auto flex max-w-4xl flex-col items-center text-center">
          <span className="mb-8 rounded-full border border-indigo-500/40 px-4 py-1.5 text-sm font-medium text-indigo-300">
            AI-Powered Packing
          </span>

          <h1 className="text-6xl font-bold tracking-tight md:text-7xl">
            <span className="block">Pack Smarter.</span>
            <span className="block bg-gradient-to-r from-indigo-500 to-purple-600 bg-clip-text text-transparent">
              Travel Better.
            </span>
          </h1>

          <p className="mt-6 max-w-2xl text-lg text-slate-400">
            AI generates your perfect packing list in seconds — personalized
            to your destination, weather, and travel style.
          </p>

          <div className="mt-10 flex flex-col items-center gap-4 sm:flex-row">
            <Link
              href="/sign-up"
              className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 px-6 py-3 text-sm font-semibold text-white transition-opacity hover:opacity-90"
            >
              Get Started Free
              <ArrowRight className="size-4" />
            </Link>
            <Link
              href="#how-it-works"
              className="flex items-center gap-2 rounded-xl px-6 py-3 text-sm font-semibold text-slate-300 transition-colors hover:bg-slate-900 hover:text-white"
            >
              See How It Works
              <ChevronRight className="size-4" />
            </Link>
          </div>

          <div className="mt-16 flex flex-wrap items-center justify-center gap-3">
            {["10k+ Trips Planned", "2 min Setup", "Smart AI Learning"].map(
              (stat) => (
                <span
                  key={stat}
                  className="rounded-xl border border-slate-800 bg-slate-900 px-4 py-2 text-sm text-slate-400"
                >
                  {stat}
                </span>
              )
            )}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how-it-works" className="px-6 py-24">
        <div className="mx-auto max-w-6xl">
          <div className="text-center">
            <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
              Three steps to perfect packing
            </h2>
            <p className="mt-4 text-slate-400">
              From trip details to a checked-off list, PackMind handles the
              rest.
            </p>
          </div>

          <div className="mt-16 grid grid-cols-1 gap-6 md:grid-cols-3">
            {steps.map((step) => (
              <div
                key={step.number}
                className="rounded-xl border border-slate-800 bg-slate-900 p-8"
              >
                <div className="text-4xl font-bold text-indigo-500">
                  {step.number}
                </div>
                <h3 className="mt-4 text-xl font-bold text-white">
                  {step.title}
                </h3>
                <p className="mt-2 text-slate-400">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="px-6 py-24">
        <div className="mx-auto max-w-6xl">
          <div className="text-center">
            <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
              Everything your packing needs
            </h2>
          </div>

          <div className="mt-16 grid grid-cols-1 gap-6 sm:grid-cols-2">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="rounded-xl border border-slate-800 bg-slate-900 p-8"
              >
                <feature.icon className="size-6 text-indigo-500" />
                <h3 className="mt-4 text-xl font-bold text-white">
                  {feature.title}
                </h3>
                <p className="mt-2 text-slate-400">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="px-6 py-24">
        <div className="mx-auto max-w-5xl rounded-xl bg-gradient-to-r from-indigo-600 to-purple-700 px-8 py-16 text-center">
          <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
            Start packing smarter today
          </h2>
          <p className="mx-auto mt-4 max-w-xl text-indigo-100">
            Join thousands of travelers who never overpack or forget
            essentials again.
          </p>
          <Link
            href="/sign-up"
            className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3 text-sm font-semibold text-slate-900 transition-opacity hover:opacity-90"
          >
            Create Your First Trip
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-800 px-6 py-8">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 sm:flex-row">
          <div className="flex items-center gap-2">
            <Luggage className="size-4 text-indigo-500" />
            <span className="font-bold">PackMind</span>
            <span className="text-sm text-slate-400">
              © {new Date().getFullYear()} PackMind. All rights reserved.
            </span>
          </div>
          <div className="flex items-center gap-6 text-sm text-slate-400">
            <Link href="#features" className="hover:text-white">
              Features
            </Link>
            <Link href="/sign-in" className="hover:text-white">
              Sign In
            </Link>
            <Link href="/sign-up" className="hover:text-white">
              Sign Up
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
