import Link from "next/link";
import { auth } from "@clerk/nextjs/server";
import {
  ArrowRight,
  Brain,
  Cloud,
  LayoutTemplate,
  MessageSquare,
  PackageOpen,
  Share2,
} from "lucide-react";
import { HeroSearchBar, TypewriterBadge } from "@/components/landing/hero-interactive";
import { AtmosphericBackground } from "@/components/atmospheric-background";

const steps = [
  {
    number: "01",
    title: "Tell us about your trip",
    description:
      "Chat naturally with our AI — destination, dates, trip type, and what you'll be doing.",
  },
  {
    number: "02",
    title: "AI builds your packing list",
    description:
      "Claude factors in live weather, your destination, and your travel style to build a list that's actually useful.",
  },
  {
    number: "03",
    title: "Pack with confidence",
    description:
      "Check items off as you go, get reminders before departure, and never scramble at the airport again.",
  },
];

const features = [
  {
    icon: Brain,
    title: "AI Packing Lists",
    description:
      "Personalized packing lists generated by Claude AI for every trip you plan.",
  },
  {
    icon: Cloud,
    title: "Live Weather Data",
    description:
      "Real forecasts for your destination shape exactly what you need to bring.",
  },
  {
    icon: MessageSquare,
    title: "SMS Reminders",
    description:
      "Get a text before departure so nothing important gets left behind.",
  },
  {
    icon: PackageOpen,
    title: "Unpack Mode",
    description:
      "Track what you actually used to make your next packing list even smarter.",
  },
  {
    icon: LayoutTemplate,
    title: "Trip Templates",
    description:
      "Save your favorite packing setups and reuse them for future trips.",
  },
  {
    icon: Share2,
    title: "Shareable Lists",
    description:
      "Share packing lists with travel companions in a single click.",
  },
];

const DESTINATION_ROW_1 = [
  "Bali",
  "Tokyo",
  "Paris",
  "New York",
  "Rome",
  "Santorini",
  "Dubai",
  "London",
];

const DESTINATION_ROW_2 = [
  "Maldives",
  "Barcelona",
  "Sydney",
  "Bangkok",
  "Amsterdam",
  "Prague",
  "Lisbon",
];

const PRESS_LOGOS = ["Forbes", "TechCrunch", "Product Hunt", "The Verge"];

export default async function Home() {
  const { userId } = await auth();

  return (
    <div className="min-h-screen text-white">
      <AtmosphericBackground intense />

      {/* Navbar */}
      <header className="fixed top-0 z-50 w-full">
        <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6">
          <Link href="/" className="text-xl font-bold tracking-tight text-white">
            PackMind
          </Link>

          <div className="flex items-center gap-4">
            {userId ? (
              <Link
                href="/dashboard"
                className="rounded-full bg-white px-5 py-2.5 text-sm font-semibold text-black transition-colors hover:bg-white/90"
              >
                Go to Dashboard
              </Link>
            ) : (
              <>
                <Link
                  href="/sign-in"
                  className="text-sm font-medium text-white/70 transition-colors hover:text-white"
                >
                  Log in
                </Link>
                <Link
                  href="/sign-up"
                  className="rounded-full bg-white px-5 py-2.5 text-sm font-semibold text-black transition-colors hover:bg-white/90"
                >
                  Get started free
                </Link>
              </>
            )}
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="relative flex min-h-screen flex-col items-center justify-center overflow-hidden px-6 text-center">
        <div className="relative mx-auto max-w-4xl">
          <TypewriterBadge />

          <h1 className="mt-6 text-6xl font-bold tracking-tight text-white md:text-8xl">
            Pack anything. Miss nothing.
          </h1>

          <p className="mx-auto mt-4 max-w-lg text-xl text-white/60">
            AI builds your perfect packing list in seconds — personalized to
            your destination, weather, and travel style.
          </p>

          <HeroSearchBar />

          <p className="mt-6 text-sm text-white/40">
            Free forever &middot; No credit card &middot; 10k+ trips planned
          </p>
        </div>
      </section>

      {/* Scrolling destinations */}
      <section className="overflow-hidden border-y border-white/5 bg-[#0a0a0a] py-12">
        <p className="mb-8 text-center text-sm font-medium uppercase tracking-widest text-white/30">
          Trusted by travelers going to
        </p>
        <div className="flex flex-col gap-4">
          <div className="flex w-max gap-3 animate-marquee">
            {[...DESTINATION_ROW_1, ...DESTINATION_ROW_1].map((city, index) => (
              <span
                key={`${city}-${index}`}
                className="shrink-0 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-white/60"
              >
                {city}
              </span>
            ))}
          </div>
          <div className="flex w-max gap-3 animate-marquee-reverse">
            {[...DESTINATION_ROW_2, ...DESTINATION_ROW_2].map((city, index) => (
              <span
                key={`${city}-${index}`}
                className="shrink-0 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-white/60"
              >
                {city}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how-it-works" className="bg-[#111111] px-6 py-24 sm:py-32">
        <div className="mx-auto max-w-6xl">
          <h2 className="text-center text-3xl font-bold tracking-tight text-white md:text-5xl">
            How it works
          </h2>

          <div className="mt-24 grid grid-cols-1 gap-16 md:grid-cols-3 md:gap-8">
            {steps.map((step) => (
              <div key={step.number} className="relative">
                <span className="pointer-events-none absolute -top-16 left-1/2 -translate-x-1/2 text-[10rem] leading-none font-bold text-white/5 select-none md:left-0 md:-translate-x-0">
                  {step.number}
                </span>
                <div className="relative pt-10 text-center md:text-left">
                  <p className="text-sm font-bold text-indigo-400">
                    {step.number}
                  </p>
                  <h3 className="mt-2 text-xl font-bold text-white">
                    {step.title}
                  </h3>
                  <p className="mt-3 text-base text-white/50">
                    {step.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="bg-[#0a0a0a] px-6 py-24 sm:py-32">
        <div className="mx-auto max-w-6xl">
          <h2 className="text-center text-3xl font-bold tracking-tight text-white md:text-5xl">
            Everything your packing needs
          </h2>

          <div className="mt-16 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="rounded-2xl border border-white/10 bg-white/5 p-6 transition-colors hover:border-white/20 hover:bg-white/8"
              >
                <div className="flex size-12 items-center justify-center rounded-xl bg-indigo-500/10">
                  <feature.icon className="size-6 text-indigo-400" />
                </div>
                <h3 className="mt-5 text-lg font-bold text-white">
                  {feature.title}
                </h3>
                <p className="mt-2 text-sm text-white/50">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Social proof */}
      <section className="bg-[#0a0a0a] px-6 pb-24 sm:pb-32">
        <div className="mx-auto max-w-4xl text-center">
          <p className="text-sm font-medium uppercase tracking-widest text-white/30">
            As seen in
          </p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-x-12 gap-y-4">
            {PRESS_LOGOS.map((name) => (
              <span
                key={name}
                className="text-xl font-bold tracking-tight text-white/20"
              >
                {name}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-[#0a0a0a] px-6 pb-24 sm:pb-32">
        <div className="mx-auto max-w-5xl rounded-3xl bg-gradient-to-br from-indigo-600 to-violet-600 px-8 py-16 text-center sm:px-16">
          <h2 className="text-3xl font-bold tracking-tight text-white md:text-5xl">
            Start packing smarter
          </h2>
          <p className="mx-auto mt-4 max-w-xl text-lg text-white/80">
            Create your first AI packing list in under 2 minutes.
          </p>
          <Link
            href="/sign-up"
            className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-indigo-600 transition-colors hover:bg-white/90"
          >
            Get started free
            <ArrowRight className="size-4" />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-[#080808] px-6 py-12">
        <div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 text-center sm:flex-row sm:text-left">
          <span className="text-lg font-bold tracking-tight text-white">
            PackMind
          </span>

          <div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm text-white/30">
            <Link href="#features" className="transition-colors hover:text-white/60">
              Features
            </Link>
            <Link href="#how-it-works" className="transition-colors hover:text-white/60">
              How it Works
            </Link>
            <Link href="/templates" className="transition-colors hover:text-white/60">
              Templates
            </Link>
            <Link href="/sign-in" className="transition-colors hover:text-white/60">
              Sign in
            </Link>
          </div>

          <p className="text-sm text-white/30">
            &copy; {new Date().getFullYear()} PackMind
          </p>
        </div>
      </footer>
    </div>
  );
}
